  <x-app-layout>
    <campaings-main
      :agencies="{{$agencies}}"
      :bussiness="{{$bussiness}}"
      :campaigns="{{$campaigns}}"
      :user="{{$user}}"
      :combos="{{$combos}}">
    </campaings-main>
  </x-app-layout>
